# Generated by Django 4.2.5 on 2023-12-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("contactid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("desc", models.TextField(max_length=500)),
                ("phone", models.IntegerField()),
            ],
        ),
    ]
